name: Generate Wallpaper Github README.md

on:
  workflow_dispatch:
    
  schedule:
    - cron: "0 3 * * *"
  

jobs:
 Generate_Wallpaper :
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Generate Wallpaper Himawari
      run: ./himawari.ps1
      shell: pwsh
    - name: timestamp Himawari  
      run: Write-Output (Get-ChildItem ./Himawari/latest.jpg -Force | Select-Object LastWriteTime | Get-Date) | Out-File ./Himawari/timestamp
      shell: pwsh
    - name: Generate Wallpaper BingWallpaper
      run: ./bing-wallpaper.ps1
      shell: pwsh
    - name: timestamp BingWallpaper   
      run: Write-Output (Get-ChildItem ./BingWallpaper/latest.jpg -Force | Select-Object LastWriteTime | Get-Date) | Out-File ./BingWallpaper/timestamp
      shell: pwsh
    - name: Deploy
      run: |
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name ${{ secrets.NAME }}
        git add .
        git commit -m "set wallpaper"
        git push
        

 auto-update-readme:
      runs-on: ubuntu-latest
      needs: Generate_Wallpaper
      steps:
        - name: Markdown autodocs
          uses: dineshsonachalam/markdown-autodocs@v1.0.3      
      
        

