name: Generate Wallpaper Github README.md

on:
  workflow_dispatch:
    
  schedule:
    - cron: "0 3 * * *"
  

jobs:
 Generate_Wallpaper :
    runs-on: windows-latest
    timeout-minutes: 10


    steps:
    - uses: actions/checkout@v2
    - name: Generate Wallpaper Himawari
      run: ./himawar.ps1
      shell: pwsh
    - name: timestamp Himawari  
      run: Write-Output (Get-ChildItem ./Himawari/latest.jpg -Force | Select-Object LastWriteTime | Get-Date) | Out-File ./Himawari/timestamp
      shell: pwsh
    - name: Generate Wallpaper BingWallpaper
      run: ./bing-wallpaper.ps1
      shell: pwsh
    - name: timestamp BingWallpaper   
      run: Write-Output (Get-ChildItem ./BingWallpaper/latest.jpg -Force | Select-Object LastWriteTime | Get-Date) | Out-File ./BingWallpaper/timestamp
      shell: pwsh
    - name: timestamp to readme   
      run: |
       $prefix = "- ##### "
       $bingdate = Get-ChildItem ./BingWallpaper/latest.jpg -Force | Select-Object LastWriteTime | Get-Date -UFormat "%A %d/%m/%Y %T %Z"
       $HimawariDate = Get-ChildItem ./Himawari/latest.jpg -Force | Select-Object LastWriteTime | Get-Date -UFormat "%A %d/%m/%Y %T %Z"
       $textToAdd = "$($prefix)$($bingdate)"
       $textToAdd2 = "$($prefix)$($HimawariDate)"
       $BingLineNumber = 4
       $HimawariLineNumber = 9
       $fileContent = Get-Content ./README.md
       $fileContent[$BingLineNumber-1] = $textToAdd
       $fileContent[$HimawariLineNumber-1] = $textToAdd2
       $fileContent | Set-Content ./README.md
       
    - name: Deploy
      run: |
       git config --global user.email ${{ secrets.EMAIL }}
       git config --global user.name ${{ secrets.NAME }}
       git add .
       git commit -m "set wallpaper"
       git push
      


