name: bw2

on:
  workflow_dispatch:
    

  

jobs:
 Generate_Wallpaper :
    runs-on: windows-latest
    timeout-minutes: 10


    steps:
    - uses: actions/checkout@v2
    - name: Generate Wallpaper BingWallpaper
      shell: pwsh
      run: |
       cd ./executables/BING_2
       dir

