name: bw2

on:
  workflow_dispatch:
    

  

jobs:
 Generate_Wallpaper :
    runs-on: windows-latest
    timeout-minutes: 10


    steps:
    - uses: actions/checkout@v2
    - name: Generate Wallpaper BingWallpaper
      shell: pwsh
      run: |
       cd ./executables/BING_2
       ./bing-wallpaper.ps1
       Move-Item -Path C:\Users\runneradmin\Pictures\BingWallpaper\*.jpg -Destination ./executables/BING_2/latest.jpg
       dir

