name: bw2

on:
  workflow_dispatch:
    

  

jobs:
 Generate_Wallpaper :
    runs-on: windows-latest
    timeout-minutes: 10


    steps:
    - uses: actions/checkout@v2
    - name: Generate Wallpaper BingWallpaper
      shell: pwsh
      run: |
       cd ./executables/BING_2
       dir
       Add-Type -Assembly System.Web | Out-Null
       $BW = New-Object Net.WebClient
       $BW.Encoding = [Text.Encoding]::UTF8
       $json = ConvertFrom-Json ($BW.DownloadString('https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US'))
       $url = 'https://www.bing.com{0}_1920x1080.jpg' -f $json.images.urlbase
			 $copyright = ($json.images.copyright)

       $startdate = ($json.images.startdate)
       $shortname = ($urlbase -match '/th\?id=OHR.(.*)$') | Foreach {$Matches[1].split('_')[0]}
       $author = $copyright.split('()')[1].split([IO.Path]::GetInvalidFileNameChars()) -join '_'
       $ImageFileName = "$($shortname)_$($startdate)($($author)).jpg"
       $title = ($json.images.title)
       $description = $copyright.split('()')[0].split([IO.Path]::GetInvalidFileNameChars()) -join ''
       Write-Host url:($url)
        Write-Host copyright:($copyright)
        Write-Host startdate:($startdate)
        Write-Host shortname:($shortname)
        Write-Host author:($author)
        Write-Host ImageFileName:($ImageFileName) 
        Write-Host description:($description) 
        Write-Host title:($title)
        $BW.DownloadFile($url,$ImageFileName)
        dir
