name: bw2

on:
  workflow_dispatch:
    
jobs:
 Generate_Wallpaper :
    runs-on: windows-latest
    timeout-minutes: 10
    strategy:
     fail-fast: false
     matrix:
      pro: [powershell,pwsh]

    steps:
    - uses: actions/checkout@v2
    - name: Generate Wallpaper BingWallpaper
      shell: ${{ matrix.pro }}
      run: |
       $textToAdd = '$outpath = "./executables/BING_2"'
       $BingLineNumber = 42
       $fileContent = Get-Content ./executables/BING_2/bing-wallpaper.ps1
       $fileContent[$BingLineNumber-1] = $textToAdd
       $fileContent | Set-Content ./executables/BING_2/bing-wallpaper.ps1
       $textToAdd2 = ' <debug>true</debug>'
       $BingLineNumber2 = 11
       $fileContent2 = Get-Content ./executables/BING_2/SettingsBw.xml
       $fileContent2[$BingLineNumber2-1] = $textToAdd2
       $fileContent2 | Set-Content ./executables/BING_2/SettingsBw.xml      
       cd ./executables/BING_2
       ./bing-wallpaper.ps1

       
       dir
 
