name: bw2

on:
  workflow_dispatch:
    

  

jobs:
 Generate_Wallpaper :
    runs-on: windows-latest
    timeout-minutes: 10


    steps:
    - uses: actions/checkout@v2
    - name: Generate Wallpaper BingWallpaper
      shell: powershell
      run: |

       $textToAdd2 = ' <debug>true</debug>'
       $BingLineNumber2 = 11
       $fileContent2 = Get-Content ./executables/BING_2/SettingsBw.xml
       $fileContent2[$BingLineNumber2-1] = $textToAdd2
       $fileContent2 | Set-Content ./executables/BING_2/SettingsBw.xml      
       cd ./executables/BING_2
       ./bing-wallpaper.ps1
       cd /
       cd $outpath
       Move-Item -Path "$outpath/*.jpg" -Destination "./executables/BING_2"
       cd ./executables/BING_2
       dir

