name: bw2

on:
  workflow_dispatch:
    
jobs:
 Generate_Wallpapers :
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Generate Wallpaper Bing
      shell: powershell
      run: |
       $textToAdd = '$outpath = "./executables/BING_2"'
       $BingLineNumber = 42
       $fileContent = Get-Content ./executables/BING_2/bing-wallpaper.ps1
       $fileContent[$BingLineNumber-1] = $textToAdd
       $fileContent | Set-Content ./executables/BING_2/bing-wallpaper.ps1
       $textToAdd2 = ' <debug>true</debug>'
       $BingLineNumber2 = 11
       $fileContent2 = Get-Content ./executables/BING_2/SettingsBw.xml
       $fileContent2[$BingLineNumber2-1] = $textToAdd2
       $fileContent2 | Set-Content ./executables/BING_2/SettingsBw.xml
       
       cd ./executables/BING_2
       ./bing-wallpaper.ps1
       Write-Output pred
       dir -r | Select-Object Name,Length,LastWriteTime
       Write-Output po
       Get-ChildItem *.jpg | Rename-Item -NewName { $_.Name -replace '.*.jpg','latest.jpg' }
       dir -r | Select-Object Name,Length,LastWriteTime
       
    - name: Generate Wallpaper Himawari
      shell: powershell
      run: |
       $textToAdd = '$outpath = "./Himawari/"'
       $HimawariLineNumber = 30
       $fileContent = Get-Content ./executables/Himawari/himawari.ps1
       $fileContent[$HimawariLineNumber-1] = $textToAdd
       $fileContent | Set-Content ./executables/Himawari/himawari.ps1

       cd ./executables/Himawari
       ./himawari.ps1
       Write-Output pred
       dir -r | Select-Object Name,Length,LastWriteTime
       Write-Output po
       Get-ChildItem *.jpg | Rename-Item -NewName { $_.Name -replace '.*.jpg','latest.jpg' }
       dir -r | Select-Object Name,Length,LastWriteTime       