name: bw2

on:
  workflow_dispatch:
    
jobs:
 Generate_Wallpapers :
    runs-on: windows-latest
    timeout-minutes: 10
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2

       
       
    - name: Generate Wallpaper Himawari
      shell: pwsh
      run: |
       $textToAdd = '$outpath = "./Himawari/"'
       $HimawariLineNumber = 30
       $fileContent = Get-Content ./executables/Himawari/himawari.ps1
       $fileContent[$HimawariLineNumber-1] = $textToAdd
       $fileContent | Set-Content ./executables/Himawari/himawari.ps1

       
       Write-Output pred
       dir -r | Select-Object Name,Length,LastWriteTime
       ./executables/Himawari/himawari.ps1
       Write-Output po
       Get-ChildItem *.jpg | Rename-Item -NewName { $_.Name -replace '.*.jpg','latest.jpg' }
       dir -r | Select-Object Name,Length,LastWriteTime       