name: ps1ToExe Test Matrix

on: [repository_dispatch,workflow_dispatch]

jobs:
 windows_executable:
    runs-on: windows-latest
    strategy:
      max-parallel: 3
      matrix:
        include:
           - path: executables/BING_2
             script: bing-wallpaper.ps1
           - path: executables/Himawari
             script: himawari.ps1
           - path: executables/LigtDark
             script: LigtDark.ps1

    steps:
    - uses: actions/checkout@v3
    - name: Version
      run: |
       $version = (Get-Content ./${{ matrix.path }}/${{ matrix.script }} -First 1).split('# (v)').split([IO.Path]::GetInvalidFileNameChars()) -join ''
       Write-Output $version
       echo $version
       echo ----------------------
       $short = ${{ matrix.script }} -split(".ps1")
       Write-Output $short
       echo $short
       echo ----------------------
       Write-Output "Converts powershell scripts to standalone executables."
       ./executables/ps2exe.ps1 -inputFile ./${{ matrix.path }}/${{ matrix.script }} -outputFile ./${{ matrix.path }}/$short.exe -noConsole -title $short -iconFile ./${{ matrix.path }}/$short.ico -version $version
      shell: powershell

    - name: upload-artifacts
      uses: actions/upload-artifact@v3
      with:
        name: files
        path: |
        ./${{ matrix.path }}/${{ matrix.script }}
        ./${{ matrix.path }}/*.exe
        ./${{ matrix.path }}/*.xml