name: ps1ToExe Test Matrix

on: [repository_dispatch,workflow_dispatch]

jobs:
 windows_executable:
    outputs:
     output1: ${{ steps.Version.outputs.version }}
     output2: ${{ steps.Version.outputs.short }}
    runs-on: windows-latest
    strategy:
      max-parallel: 3
      matrix:
        include:
           - path: executables/BING_2
             script: bing-wallpaper.ps1
           - path: executables/Himawari
             script: himawari.ps1
           - path: executables/LigtDark
             script: LigtDark.ps1

    steps:
    - uses: actions/checkout@v3
    - name: Version
      id: Version
      run: |
       $version = (Get-Content ./${{ matrix.path }}/${{ matrix.script }} -First 1).split('# (v)').split([IO.Path]::GetInvalidFileNameChars()) -join ''
       Write-Output $version
       echo $version
       echo ----------------------
       $shortX = "${{ matrix.script }} "-split(".ps1") -join ''
       $short = $shortX.Trim()
       Write-Output $short
       echo $short
       echo ----------------------
       echo "version=$(echo $version)" >> $GITHUB_OUTPUT
       echo "short=$(echo $short)" >> $GITHUB_OUTPUT
       echo "version=$(echo $version)" >> $GITHUB_ENV
       echo "short=$(echo $short)" >> $GITHUB_ENV
      shell: powershell

    - name: Build
      run: |
       echo ${{ env.short }}
       echo ${{ steps.Version.outputs.short }}
       echo $short
       echo ----------------------

      shell: powershell
      env:
        short: ${{ env.short }}

    - name: upload-artifacts
      uses: actions/upload-artifact@v3
      with:
        name: files
        path: |
         ./${{ matrix.path }}/${{ matrix.script }}
         ./${{ matrix.path }}/*.exe
         ./${{ matrix.path }}/*.xml