# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://github.com/microsoft/action-psscriptanalyzer
# For more information on PSScriptAnalyzer in general, see
# https://github.com/PowerShell/PSScriptAnalyzer

name: PSScriptAnalyzer

on:
  workflow_dispatch:

  pull_request:
    branches: [ main ]

jobs:
  build:
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.HimawariSum }}
      output2: ${{ steps.step1.outputs.BingSum }}
    strategy:
      max-parallel: 3
      matrix:
        include:
           - path: executables/BING_2
             script: bing-wallpaper.ps1
           - path: executables/Himawari
             script: himawari.ps1

    steps:
      - uses: actions/checkout@v2
      - name: details
        env:
          path: ${{ matrix.path }}
          script: ${{ matrix.script }}
        run: |
         echo $path $script
         echo 'artifact (.ps1.bak)'
         cp ./${{ matrix.path }}/${{ matrix.script }}{,.bak}


      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@2044ae068e37d0161fa2127de04c19633882f061
        with:
          # Check https://github.com/microsoft/action-psscriptanalyzer for more info about the options.
          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
          # Include your own basic security rules. Removing this option will run all the rules
          # includeRule: ''
          # excludeRule: '"PSAvoidUsingWriteHost", "PSAvoidTrailingWhitespace"'
          output: ./${{ matrix.path }}/${{ matrix.script }}.results.sarif
          path: ./${{ matrix.path }}/${{ matrix.script }}
          recurse: false
          fix: true

      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./${{ matrix.path }}/${{ matrix.script }}.results.sarif
      # Artifacts upload
      - uses: actions/upload-artifact@v2
        with:
         path: |
          ./${{ matrix.path }}/*.sarif
          ./${{ matrix.path }}/${{ matrix.script }}
          ./${{ matrix.path }}/${{ matrix.script }}.bak

      - name: Update scripts
        run: |
         $timestamp= (Get-Date -UFormat "%A %d/%m/%Y %T %Z")
         echo $timestamp
         git config --global user.email ${{ secrets.EMAIL }}
         git config --global user.name ${{ secrets.NAME }}
         git add -u
         git commit -m "PSScriptAnalyzer $timestamp"
         git push