# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://github.com/microsoft/action-psscriptanalyzer
# For more information on PSScriptAnalyzer in general, see
# https://github.com/PowerShell/PSScriptAnalyzer

name: PSScriptAnalyzer

on:
  workflow_dispatch:
    
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest 
    strategy:
      max-parallel: 3
      matrix:
        include:
           - path: ./executables/BING_2/bing-wallpaper.ps1
             script: bing-wallpaper.ps1
           - path: ./executables/Himawari/himawari.ps1
             script: himawari.ps1
           
    steps:
      - uses: actions/checkout@v2
      - name: Echo site details
        env:
          path: ${{ matrix.path }}
          script: ${{ matrix.script }}
        run: echo $path $script

     # upload artifact (.ps1.bak)
      - name: Create .bak files
        run: |
         cp ${{ matrix.path }}{,.bak}
      - uses: actions/upload-artifact@v2 
        with:
         name: prebuild
         path: |       
          ${{ matrix.path }}.bak
          
      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@2044ae068e37d0161fa2127de04c19633882f061
        with:
          # Check https://github.com/microsoft/action-psscriptanalyzer for more info about the options.
          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
          # Include your own basic security rules. Removing this option will run all the rules 
          # includeRule: ''
          # excludeRule: '"PSAvoidUsingWriteHost", "PSAvoidTrailingWhitespace"'
          output: ${{ matrix.script }}.results.sarif
          path: ${{ matrix.path }}       
          recurse: true
          fix: true
      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ matrix.script }}.results.sarif
      # Artifacts upload     
      - uses: actions/upload-artifact@v2 
        with:
         name: prebuild
         path: |
          ./*.sarif
          ${{ matrix.path }}


     # Artifacts download  
      - uses: actions/download-artifact@v2
        id: download
        with:
         name: prebuild
         path: ./
     # tree 
      - name: Display structure of downloaded files 
        run: tree -h ./ 
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
     # virustotal
      - name: virustotal
        run: |
         sha256sum ${{ matrix.path }} | cut -f 1 -d " "       
         sum=$(sha256sum ${{ matrix.path }} | cut -f 1 -d " ")
         echo $sum
         echo UPLOAD
