# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://github.com/microsoft/action-psscriptanalyzer
# For more information on PSScriptAnalyzer in general, see
# https://github.com/PowerShell/PSScriptAnalyzer

name: PSScriptAnalyzer

on:
  workflow_dispatch:
    
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        include:
<<<<<<< HEAD
           - path: ./executables/BING_2/bing-wallpaper.ps1
             script: bing-wallpaper.ps1
           - path: ./executables/Himawari/himawari.ps1
             script: himawari.ps1
=======
          -  path: ./executables/BING_2/himawari.ps1
             script: himawari.ps1
 
          -  path: ./executables/Himawari/bing-wallpaper.ps1
             script: bing-wallpaper.ps1
>>>>>>> 86ad859978608b32967d67a70eb32a0082224941
           
    steps:
      - name: Echo site details
        env:
          path: ${{ matrix.path }}
          script: ${{ matrix.script }}
        run: echo $path $script

     # upload artifact (.ps1.bak)
      - name: Create .bak files
        run: |
         cp ${{ matrix.path }}{,.bak}
      - uses: actions/upload-artifact@v2 
        with:
         name: prebuild
         path: |       
          ${{ matrix.path }}.bak
