
name: release-test
run-name: ${{ github.workflow }} ✅ ${{ github.actor }} ✅ ${{ github.event_name}}
on:
  workflow_dispatch:
jobs:
  create:
    name: RELEASE CREATE
    timeout-minutes: 10
    strategy:
      max-parallel: 3
      matrix:
       os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}


    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
         path: ./artifact/

      - uses: milankomaj/releases-x@v0.1
        with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         target: main
         title: test executables
         rewrite: true
         files: |
          ./artifact/*.*
