name: Video 
on:
  workflow_dispatch:
  
 
jobs:

   
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.SCALE }}
      output2: ${{ steps.step1.outputs.PREFIX }} 
      output3: ${{ steps.step1.outputs.URL }}
    timeout-minutes: 10
    continue-on-error: true
    strategy:
      max-parallel: 3
      matrix: 
       prefix: [pir3, pifd, pijp]
  
    steps:
      - name: Checkout 
        uses: actions/checkout@v2 
      - name: himawari video prefix
        id: step1
        run: | 
         date=$(date +'%Y%m%d')
         echo date=$date
         url=(https://himawari8.nict.go.jp/movie/720/$(echo $date)_${{ matrix.prefix }}.mp4) # pir3.mp4, pifd.mp4, pijp.mp4
         echo url=$url
         size=$(curl -s $url | wc -c)
         echo size=$size
         scale=$(echo "scale=0; $size /1024/1024" | bc -l)
         echo scale=$scale
         echo "::set-output name=SCALE::$(echo $scale)"
         echo "::set-output name=PREFIX::${{ matrix.prefix }}" 
         echo "::set-output name=URL::$(echo $url)"
         

      - name: Generate pir3
        shell: bash
        if: ${{ matrix.prefix == 'pir3' }}
        run: |
          echo pir3
          if [ ${{ steps.step1.outputs.SCALE }} -ge 1 ]
          then
          sudo apt-get install -y ffmpeg
          echo "++++"
          url=$(curl -s -L -o ./Himawari/${{ steps.step1.outputs.PREFIX }}.mp4 ${{ steps.step1.outputs.URL }})
          echo url = ${{ steps.step1.outputs.URL }}
          ffmpeg -i ./Himawari/${{ steps.step1.outputs.PREFIX }}.mp4 -vf blackframe=0,metadata=select:key=lavfi.blackframe.pblack:value=90:function=less,minterpolate=mi_mode=mci:mc_mode=obmc:me_mode=bilat:vsbmc=0:me=tdls:fps=10 -c:a copy -y ./Himawari/${{ steps.step1.outputs.PREFIX }}_out.mp4
          ffmpeg -y -i ./Himawari/
          ${{ steps.step1.outputs.PREFIX }}_out.mp4 -vf fps=10,scale=680:-1:flags=lanczos,palettegen palette.png
          ffmpeg -i ./Himawari/${{ steps.step1.outputs.PREFIX }}_out.mp4 -i palette.png -filter_complex "fps=10,scale=680:-1:flags=lanczos[x];[x][1:v]paletteuse" -y ./Himawari/himawari_${{ steps.step1.outputs.PREFIX }}.gif
          ffmpeg -i ./Himawari/${{ steps.step1.outputs.PREFIX }}_out.mp4 -vcodec libwebp -preset default -loop 0 -an -vsync 0 -vf fps=10,scale=680:-1 -qscale:v 70 -y ./Himawari/himawari_${{ steps.step1.outputs.PREFIX }}.webp
          else
          echo "-----"
          fi 
      - name: Generate pifd
        shell: bash
        if: ${{ matrix.prefix == 'pifd' }}
        run: |
          echo pifd
          if [ ${{ steps.step1.outputs.SCALE }} -ge 1 ]
          then
          sudo apt-get install -y ffmpeg
          echo "++++"
          url=$(curl -s -L -o ./Himawari/${{ steps.step1.outputs.PREFIX }}.mp4 ${{ steps.step1.outputs.URL }})      
          echo url = ${{ steps.step1.outputs.URL }}
          ffmpeg -i ./Himawari/${{ steps.step1.outputs.PREFIX }}.mp4 -vcodec libwebp -preset default -loop 0 -an -vsync 0 -vf "fps=30, scale=680:720" -qscale 70 -y ./Himawari/himawari_${{ steps.step1.outputs.PREFIX }}.webp  
          ffmpeg -y -i ./Himawari/${{ steps.step1.outputs.PREFIX }}.mp4 -vf fps=10,scale=716:-1:flags=lanczos,palettegen ./Himawari/palette.png
          ffmpeg -i ./Himawari/${{ steps.step1.outputs.PREFIX }}.mp4 -i ./Himawari/palette.png -filter_complex "fps=10,scale=716:-1:flags=lanczos[x];[x][1:v]paletteuse" -y ./Himawari/himawari_${{ steps.step1.outputs.PREFIX }}.gif
          else
          echo "-----"
          fi 
      - name: Generate pijp
        shell: bash
        if: ${{ matrix.prefix == 'pijp' }}
        run: |
          echo pijp 
          if [ ${{ steps.step1.outputs.SCALE }} -ge 1 ]
          then
          sudo apt-get install -y ffmpeg
          echo "++++"
          url=$(curl -s -L -o ./Himawari/${{ steps.step1.outputs.PREFIX }}.mp4 ${{ steps.step1.outputs.URL }})
          echo url = ${{ steps.step1.outputs.URL }}
          ffmpeg -i ./Himawari/${{ steps.step1.outputs.PREFIX }}.mp4 -vf blackframe=0,metadata=select:key=lavfi.blackframe.pblack:value=90:function=less,minterpolate=mi_mode=mci:mc_mode=obmc:me_mode=bilat:vsbmc=0:me=tdls:fps=10 -c:a copy -y ./Himawari/${{ steps.step1.outputs.PREFIX }}_out.mp4
          ffmpeg -y -i ./Himawari/${{ steps.step1.outputs.PREFIX }}_out.mp4 -vf fps=10,scale=680:-1:flags=lanczos,palettegen palette.png
          ffmpeg -i ./Himawari/${{ steps.step1.outputs.PREFIX }}_out.mp4 -i palette.png -filter_complex "fps=10,scale=680:-1:flags=lanczos[x];[x][1:v]paletteuse" -y ./Himawari/himawari_${{ steps.step1.outputs.PREFIX }}.gif
          ffmpeg -i ./Himawari/${{ steps.step1.outputs.PREFIX }}_out.mp4 -vcodec libwebp -preset default -loop 0 -an -vsync 0 -vf fps=10,scale=680:-1 -qscale:v 70 -y ./Himawari/himawari_${{ steps.step1.outputs.PREFIX }}.webp
          else
          echo "-----"
          fi                  
      - name: tree
        run: |
         tree -h ./Himawari/         