name: Video 
on:
  workflow_dispatch:
  
 
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.SCALE }} 
    timeout-minutes: 10 
    strategy:
      matrix: 
       prefix: [pir3]
  
    steps:          
      - name: himawari video prefix 
        id: step1
        run: | 
         date=$(date +'%Y%m%d')
         echo date=$date
         url=(https://himawari8.nict.go.jp/movie/720/$(echo $date)_${{ matrix.prefix }}.mp4) # pir3.mp4, pifd.mp4, pijp.mp4
         echo url=$url
         size=$(curl -s $url | wc -c)
         echo size=$size
         scale=$(echo "scale=0; $size /1024/1024" | bc -l)
         echo scale=$scale
         echo "::set-output name=SCALE::$(echo $scale)" 
         echo ${{steps.step1.outputs.SCALE}}
        
      - name: script
        run: | 
         echo ${{ matrix.prefix }}
         echo ${{steps.step1.outputs.SCALE}}
         echo ${{needs.build.outputs.output1}}
        
         if [ ${{steps.step1.outputs.SCALE}} -ge 1 ]
         then
         echo "++++"
         else
         echo "-----"
         fi
