name: Video 
on:
  workflow_dispatch:
  
 
jobs:

   
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.SCALE }}
      output2: ${{ steps.step1.outputs.PREFIX }} 
      output3: ${{ steps.step1.outputs.URL }}
    timeout-minutes: 10 
    strategy:
      max-parallel: 3
      matrix: 
       prefix: [pir3, pifd, pijp]
  
    steps:     
      - name: himawari video prefix 
        id: step1
        run: | 
         date=$(date +'%Y%m%d')
         echo date=$date
         url=(https://himawari8.nict.go.jp/movie/720/$(echo $date)_${{ matrix.prefix }}.mp4) # pir3.mp4, pifd.mp4, pijp.mp4
         echo url=$url
         size=$(curl -s $url | wc -c)
         echo size=$size
         scale=$(echo "scale=0; $size /1024/1024" | bc -l)
         echo scale=$scale
         echo "::set-output name=SCALE::$(echo $scale)"
         echo "::set-output name=PREFIX::${{ matrix.prefix }}" 
         echo "::set-output name=URL::$(echo $url)"
         
         sudo apt-get install -y ffmpeg

      - name: script
        run: | 
         echo ${{steps.step1.outputs.SCALE}}
         echo ${{steps.step1.outputs.PREFIX}}
         echo ${{steps.step1.outputs.URL}}

         if [ ${{steps.step1.outputs.SCALE}} -ge 1 ]
         then
         echo "++++"
         else
         echo "----"      
         fi

         if [ ${{steps.step1.outputs.PREFIX}} = pifd ]
         then
         curl -s -L -o himawari_${{steps.step1.outputs.PREFIX}}.mp4 ${{steps.step1.outputs.URL}}

         echo -e "\033[31;1m FFmpeg webp: \033[0m"
         ffmpeg -i ./Himawari/himawari_${{steps.step1.outputs.PREFIX}}.mp4 -vcodec libwebp -preset default -loop 0 -an -vsync 0 -vf "fps=10, scale=680:720" -qscale 70 -y ./Himawari/himawari_${{steps.step1.outputs.PREFIX}}.webp  
         echo -e "\033[31;1m FFmpeg gif: \033[0m"
         ffmpeg -y -i ./Himawari/himawari_${{steps.step1.outputs.PREFIX}}.mp4 -vf fps=10,scale=716:-1:flags=lanczos,palettegen ./Himawari/palette.png
         ffmpeg -i ./Himawari/himawari_${{steps.step1.outputs.PREFIX}}.mp4 -i ./Himawari/palette.png -filter_complex "fps=10,scale=716:-1:flags=lanczos[x];[x][1:v]paletteuse" -y ./Himawari/himawari_${{steps.step1.outputs.PREFIX}}.gif
         else
         echo "----"
         fi
         

      