name: WEBP & GIF
on:
  workflow_dispatch:
  schedule:
  - cron: "45 18 * * *"
jobs:
  Himawari:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    strategy:
      fail-fast: false
      max-parallel: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg && sudo apt-get install -y curl
        shell: bash    
      - name: Curl & Ffmpeg & Push
        shell: bash
        run: | 
          date=$(date +'%Y%m%d');
          SK-zone=$(TZ='Europe/Bratislava' date)
          JP-zone=$(TZ='Asia/Tokyo' date)
          echo date=$date
          echo SK-zone=$SK-zone
          echo JP-zone=$JP-zone
          date
          echo -e "\033[5;31;1m Download: \033[0m"
          url=$(curl -s -L -o ./Himawari/himawari.mp4 https://himawari8.nict.go.jp/movie/720/$(echo $date)_pifd.mp4)
          echo url = https://himawari8.nict.go.jp/movie/720/$(echo $date)_pifd.mp4
          echo -e "\033[5;31;1m FFmpeg webp: \033[0m"
          ffmpeg -i ./Himawari/himawari.mp4 -ss 1 -t 12 -vcodec libwebp -preset default -loop 0 -an -vsync 0 -vf "fps=30, scale=680:720" -qscale 70 -y ./Himawari/himawari.webp  
          echo -e "\033[5;31;1m FFmpeg gif: \033[0m"
          ffmpeg -y -i ./Himawari/himawari.mp4 -vf fps=10,scale=716:-1:flags=lanczos,palettegen ./Himawari/palette.png
          ffmpeg -ss 1 -t 12 -i ./Himawari/himawari.mp4 -i ./Himawari/palette.png -filter_complex "fps=10,scale=716:-1:flags=lanczos[x];[x][1:v]paletteuse" -y ./Himawari/himawari.gif
          echo -e "\033[5;31;1m Push: \033[0m" 
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git pull        
          git add ./Himawari/himawari.webp
          git add ./Himawari/himawari.gif
          git commit -m "$date + $zone"
          git push
