name: WEBP
on:
  workflow_dispatch:
  schedule:
  - cron: "45 2 * * *"
jobs:
  Himawari:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    strategy:
      fail-fast: false
      max-parallel: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg && sudo apt-get install -y curl
        shell: bash    
      - name: Curl & Ffmpeg & Push
        shell: bash
        run: | 
          date=$(date +'%Y%m%d');
          echo date=$date
          echo -e "\033[5;31;1m Download: \033[0m"
          url=$(curl -s -L -o ./Himawari/himawari.mp4 https://himawari8.nict.go.jp/movie/720/$(echo $date)_pifd.mp4)
          echo url=$url
          echo -e "\033[5;31;1m FFmpeg: \033[0m"
          ffmpeg -i ./Himawari/himawari.mp4 -ss 1 -t 12 -vcodec libwebp -preset default -loop 0 -an -vsync 0 -vf "fps=30, scale=680:720" -qscale 70 ./Himawari/himawari.webp
          echo -e "\033[5;31;1m Push: \033[0m" 
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}        
          git add ./Himawari/himawari.webp
          git commit -m "$date" 
          git push 